spring.application.name=pedidos360

server.port=8080

spring.datasource.url=jdbc:postgresql://pedidos360-db.c3h0ymtw1soo.us-east-1.rds.amazonaws.com:5432/pedidos360?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Postgres132!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/874f97ca-27ae-4d8a-8d52-ee96b48fd37e/v2.0

spring.security.oauth2.resourceserver.jwt.audiences=2fddb73f-5c96-454a-bd1d-763c4cc15373